name: staging

version: 1

source:
  provider: GitHub
  properties:
    branch: staging
    repository: https://github.com/Mycalinks/pos

stages:
  - name: staging
    deployments:
      pos-web-app: # POS Web App
      ec-web-app: # EC Web App
      worker-ec-order: # EC注文関連ワーカー
      worker-item: # 商品関連ワーカー
      worker-product: # 在庫関連ワーカー
      worker-transaction: # POS取引関連ワーカー
      worker-external-ec: # 外部EC関連ワーカー
      worker-scheduled: # スケジュールタスクワーカー
      worker-notification: # 通知ワーカー
      job-daily-calculate: # 日次計算ジョブ
      job-ensure-consistency: # 不整合修正ジョブ
      backend-outbox: # outbox監視

    post_deployments:
      Deploy-lambda-functions-staging: # lambdaのデプロイ
        buildspec: ./copilot/pipelines/staging/sam/buildspec.yml
