version = 0.1

[staging.deploy.parameters]
stack_name = "shopify-webhook-staging"
region = "ap-northeast-1"
capabilities = ["CAPABILITY_IAM"]
s3_bucket = "pos-staging-private-bucket"
s3_prefix = "sam/"
confirm_changeset = false
fail_on_empty_changeset = false

[production.deploy.parameters]
stack_name = "shopify-webhook-production"
region = "ap-northeast-1"
capabilities = ["CAPABILITY_IAM"]
s3_bucket = "pos-production-private-bucket"
s3_prefix = "sam/"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = [
  "Env=production",
]