import { ExtendedAccountGroup } from '@/app/auth/(dashboard)/settings/authority/page';

// 不要であれば削除してください！
export const mockAccountGroups: ExtendedAccountGroup[] = [
  {
    id: 1,
    corporation_id: null,
    display_name: 'Admin',
    description: null,
    create_account: false,
    update_corporation: false,
    admin_mode: true,
    update_store: false,
    sales_mode: true,
    update_store_setting: false,
    get_transaction_customer_info: false,
    set_transaction_manual_discount: false,
    create_transaction_return: false,
    create_buy_reception: false,
    assess_buy_transaction: false,
    finish_buy_transaction: false,
    set_buy_transaction_manual_product_price: false,
    list_item: false,
    list_product: false,
    list_inventory: false,
    list_stocking_supplier: false,
    list_stocking: false,
    list_cash_history: false,
    list_transaction: false,
    list_customer: false,
    get_stats: false,
    accountsCount: 5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 2,
    corporation_id: null,
    display_name: 'Manager',
    description: null,
    create_account: false,
    update_corporation: false,
    admin_mode: false,
    update_store: true,
    sales_mode: true,
    update_store_setting: true,
    get_transaction_customer_info: false,
    set_transaction_manual_discount: false,
    create_transaction_return: false,
    create_buy_reception: false,
    assess_buy_transaction: false,
    finish_buy_transaction: false,
    set_buy_transaction_manual_product_price: false,
    list_item: false,
    list_product: false,
    list_inventory: false,
    list_stocking_supplier: false,
    list_stocking: false,
    list_cash_history: false,
    list_transaction: false,
    list_customer: false,
    get_stats: false,
    accountsCount: 3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 3,
    corporation_id: null,
    display_name: 'Employee',
    description: null,
    create_account: false,
    update_corporation: false,
    admin_mode: false,
    update_store: false,
    sales_mode: true,
    update_store_setting: false,
    get_transaction_customer_info: true,
    set_transaction_manual_discount: true,
    create_transaction_return: true,
    create_buy_reception: false,
    assess_buy_transaction: false,
    finish_buy_transaction: false,
    set_buy_transaction_manual_product_price: false,
    list_item: true,
    list_product: true,
    list_inventory: false,
    list_stocking_supplier: false,
    list_stocking: false,
    list_cash_history: false,
    list_transaction: true,
    list_customer: true,
    get_stats: false,
    accountsCount: 0,
    created_at: new Date(),
    updated_at: new Date(),
  },
];
