version = 0.1

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "pos-staging-python-api"
s3_bucket = "pos-staging-private-bucket"
s3_prefix = "sam/"
region = "ap-northeast-1"
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "App=\"pos\" Env=\"staging\""

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "pos-production-python-api"
s3_bucket = "pos-production-private-bucket"
s3_prefix = "sam/"
region = "ap-northeast-1"
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "App=\"pos\" Env=\"production\""