# NAT Gateway（主にIP固定用）
Parameters:
  App:
    Type: String
  Env:
    Type: String

Conditions:
  IsAllowedEnvironment: !Or
    - !Equals [!Ref Env, 'staging']
    - !Equals [!Ref Env, 'production']

Resources:
  # Elastic IPを適当に作ってIP固定
  NatGatewayEIP:
    Condition: IsAllowedEnvironment
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: project
          Value: mycapos

  # NAT Gatewayを作成
  NatGateway:
    Condition: IsAllowedEnvironment
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId # EIP紐付け
      SubnetId: #パブリックサブネットを適当に一つ選ぶ
        !Select [
          0,
          !Split [',', { Fn::ImportValue: !Sub '${App}-${Env}-PublicSubnets' }],
        ]
      Tags:
        - Key: project
          Value: mycapos

  # プライベートサブネット用のルートテーブルを作成
  PrivateRouteTable:
    Condition: IsAllowedEnvironment
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue
        Fn::Sub: '${App}-${Env}-VpcId'
      Tags:
        - Key: project
          Value: mycapos
        - Key: Name
          Value: !Sub '${App}-${Env}-PriRouteTable'

  # ルートテーブルとサブネットを明示的に紐づける
  PrivateSubnetRouteTableAssociation1:
    Condition: IsAllowedEnvironment
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId:
        !Select [
          0,
          !Split [
            ',',
            { Fn::ImportValue: !Sub '${App}-${Env}-PrivateSubnets' },
          ],
        ]

  PrivateSubnetRouteTableAssociation2:
    Condition: IsAllowedEnvironment
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId:
        !Select [
          1,
          !Split [
            ',',
            { Fn::ImportValue: !Sub '${App}-${Env}-PrivateSubnets' },
          ],
        ]

  PrivateRoute:
    Condition: IsAllowedEnvironment
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
# Outputs:
#   NatGatewayId:
#     Description: NAT Gateway ID
#     Value: !Ref NatGateway
#     Export:
#       Name: !Sub '${App}-${Env}-NatGatewayId'
