Parameters:
  App:
    Type: String
  Env:
    Type: String

# 条件定義
Conditions:
  # ステージングと本番環境のみ
  IsAllowedEnvironment: !Or
    - !Equals [!Ref Env, 'staging']
    - !Equals [!Ref Env, 'production']
  IsStaging: !Equals [!Ref Env, 'staging']
  IsProduction: !Equals [!Ref Env, 'production']

Resources:
  # 汎用パブリックバケット（環境間共通） 現在はスタック管理内にないため、いつか管理内に入れたい
  # PublicBucket:
  #   Condition: IsProduction
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Sub '${App}-public-bucket'
  #     VersioningConfiguration:
  #       Status: Enabled
  #     PublicAccessBlockConfiguration:
  #       BlockPublicAcls: true
  #       BlockPublicPolicy: true
  #       IgnorePublicAcls: true
  #       RestrictPublicBuckets: true

  # 汎用パブリックバケットのDistribution
  PublicBucketDistribution:
    Condition: IsProduction
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: 'Public content for static.mycalinks.io'
        DefaultRootObject: index.html
        Aliases:
          - static.mycalinks.io
        Origins:
          - ConnectionTimeout: 10
            OriginAccessControlId: !Ref PublicBucketOriginAccessControl
            ConnectionAttempts: 3
            OriginCustomHeaders:
              - HeaderName: Myca-Server-Info
                HeaderValue: via cloud front
            DomainName: static.mycalinks.io.s3.ap-northeast-1.amazonaws.com
            OriginShield:
              Enabled: false
            OriginPath: ''
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        ViewerCertificate:
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
          AcmCertificateArn: arn:aws:acm:us-east-1:502078855105:certificate/d92eb3d1-b139-433e-a009-68d35b3d53cf
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
          OriginRequestPolicyId: !Ref PublicBucketOriginRequestPolicyNoHost
        HttpVersion: http2
        IPV6Enabled: true
        PriceClass: PriceClass_200
        Restrictions:
          GeoRestriction:
            RestrictionType: none

  PublicBucketOriginAccessControl:
    Condition: IsProduction
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${App}-public-bucket-origin-access-control'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  PublicBucketOriginRequestPolicyNoHost:
    Condition: IsProduction
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub '${App}-public-bucket-no-host-header-policy'
        Comment: 'Do not forward Host header to S3'
        CookiesConfig:
          CookieBehavior: none
        HeadersConfig:
          HeaderBehavior: none # ← Host を含めない
        QueryStringsConfig:
          QueryStringBehavior: all

  # Route 53 Record Set
  PublicBucketAliasRecord:
    Condition: IsProduction
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: mycalinks.io.
      Name: static.mycalinks.io.
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # ← CloudFront 固定のホストゾーンID
        DNSName: !GetAtt PublicBucketDistribution.DomainName

  # # 汎用プライベートバケット
  EnvPrivateBucket:
    Condition: IsAllowedEnvironment
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${App}-${Env}-private-bucket'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # CDN
  PrivateBucketDistribution:
    Condition: IsAllowedEnvironment
    # UpdateReplacePolicy: Retain
    Type: AWS::CloudFront::Distribution
    # DeletionPolicy: Retain
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: 'Private content for private.mycalinks.io'
        DefaultRootObject: index.html
        Aliases: !If
          - IsStaging
          - - staging.private-static.mycalinks.io
          - - private-static.mycalinks.io
        Origins:
          - ConnectionTimeout: 10
            OriginAccessControlId: !Ref PrivateBucketOriginAccessControl
            ConnectionAttempts: 3
            OriginCustomHeaders:
              - HeaderName: Myca-Server-Info
                HeaderValue: via cloud front
            DomainName: !GetAtt EnvPrivateBucket.DomainName
            OriginShield:
              Enabled: false
            OriginPath: ''
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        ViewerCertificate:
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
          AcmCertificateArn: arn:aws:acm:us-east-1:502078855105:certificate/732596ce-51e4-435e-8739-40bc111d0a6d
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
          OriginRequestPolicyId: !Ref PrivateBucketOriginRequestPolicyNoHost
          TrustedKeyGroups:
            - !Ref PrivateBucketKeyGroup
        HttpVersion: http2
        IPV6Enabled: true
        PriceClass: PriceClass_200
        Restrictions:
          GeoRestriction:
            RestrictionType: none

  PrivateBucketPolicy:
    Condition: IsAllowedEnvironment
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EnvPrivateBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub ${EnvPrivateBucket.Arn}/*
              - !GetAtt EnvPrivateBucket.Arn
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${PrivateBucketDistribution}
          - Effect: Allow
            Principal:
              Service: logdelivery.elasticloadbalancing.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub ${EnvPrivateBucket.Arn}/*

  PrivateBucketOriginAccessControl:
    Condition: IsAllowedEnvironment
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${App}-${Env}-private-bucket-origin-access-control'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  PrivateBucketOriginRequestPolicyNoHost:
    Condition: IsAllowedEnvironment
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub '${App}-${Env}-private-bucket-no-host-header-policy'
        Comment: 'Do not forward Host header to S3'
        CookiesConfig:
          CookieBehavior: none
        HeadersConfig:
          HeaderBehavior: none # ← Host を含めない
        QueryStringsConfig:
          QueryStringBehavior: all

  PrivateBucketKeyGroup:
    Condition: IsAllowedEnvironment
    Type: AWS::CloudFront::KeyGroup
    Properties:
      KeyGroupConfig:
        Items: !If
          - IsStaging
          - - K1CLT9OZ4PHBVZ
          - - K2OTD9RQYTKVAI
        Comment: 'KeyGroup for signed URLs'
        Name: !Sub '${App}-${Env}-private-bucket-key-group'

  # Route 53 Record Set
  PrivateBucketAliasRecord:
    Condition: IsAllowedEnvironment
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: mycalinks.io.
      Name: !If
        - IsStaging
        - staging.private-static.mycalinks.io.
        - private-static.mycalinks.io.
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # ← CloudFront 固定のホストゾーンID
        DNSName: !GetAtt PrivateBucketDistribution.DomainName
