Parameters:
  App:
    Type: String
  Env:
    Type: String

# 条件定義
Conditions:
  # ステージングと本番環境のみ
  IsAllowedEnvironment: !Or
    - !Equals [!Ref Env, 'staging']
    - !Equals [!Ref Env, 'production']
  IsStaging: !Equals [!Ref Env, 'staging']
Resources:
  # メール通知
  EmailReceiptRule:
    Condition: IsAllowedEnvironment
    Type: AWS::SES::ReceiptRule
    Properties:
      RuleSetName: mycalinks-com-rule
      Rule:
        Name: !Sub '${App}-${Env}-email-s3-rule'
        Enabled: true
        Recipients:
          # おちゃのこ
          - !If [
              IsStaging,
              'ochanoko-ec-order@mycalinks.io',
              'ochanoko-ec-order@mycalinks.com',
            ]
        Actions:
          - S3Action:
              BucketName: !Sub '${App}-${Env}-email-bucket'
              ObjectKeyPrefix: email/
        ScanEnabled: true

  # 木村さんにメール転送
  InfoMailReceiptRule:
    Condition: IsStaging
    Type: AWS::SES::ReceiptRule
    Properties:
      RuleSetName: mycalinks-com-rule
      Rule:
        Name: !Sub '${App}-${Env}-info-mail-rule'
        Enabled: true
        Recipients:
          - info@mycalinks.com
        Actions:
          - S3Action:
              BucketName: !Sub '${App}-${Env}-email-bucket'
              ObjectKeyPrefix: email/
        ScanEnabled: true
