Parameters:
  App:
    Type: String
  Env:
    Type: String

Mappings:
  VpnSetting:
    staging:
      ServerCertificateArn: arn:aws:acm:ap-northeast-1:502078855105:certificate/bf8fcc25-58c2-4b37-8b3a-55c7baa508b9
      Cidr: 10.100.0.0/16
    production:
      ServerCertificateArn: arn:aws:acm:ap-northeast-1:502078855105:certificate/70a66b22-9b12-4a1e-a482-1c4443a3cf64
      Cidr: 10.100.0.0/16

# 条件定義
Conditions:
  # ステージングと本番環境のみ
  IsAllowedEnvironment: !Or
    - !Equals [!Ref Env, 'staging']
    - !Equals [!Ref Env, 'production']
  IsStaging: !Equals [!Ref Env, 'staging']
  IsProduction: !Equals [!Ref Env, 'production']

Resources:
  ClientVpnEndpoint:
    Condition: IsAllowedEnvironment
    Type: AWS::EC2::ClientVpnEndpoint
    Properties:
      AuthenticationOptions:
        - Type: certificate-authentication
          MutualAuthentication:
            ClientRootCertificateChainArn:
              !FindInMap [VpnSetting, !Ref Env, ServerCertificateArn]
      ClientCidrBlock: !FindInMap [VpnSetting, !Ref Env, Cidr]
      ConnectionLogOptions:
        Enabled: false
      ServerCertificateArn:
        !FindInMap [VpnSetting, !Ref Env, ServerCertificateArn]
      TransportProtocol: udp
      VpnPort: 443
      SplitTunnel: true
      TagSpecifications:
        - ResourceType: client-vpn-endpoint
          Tags:
            - Key: Name
              Value: !Sub ${App}-${Env}-ClientVPNEndpoint

  ClientVpnAssociation:
    Condition: IsAllowedEnvironment
    Type: AWS::EC2::ClientVpnTargetNetworkAssociation
    Properties:
      ClientVpnEndpointId: !Ref ClientVpnEndpoint
      SubnetId: !If
        - IsStaging
        - !Select [
            0,
            !Split [
              ',',
              { Fn::ImportValue: !Sub '${App}-${Env}-PublicSubnets' },
            ],
          ]
        - !Select [
            0,
            !Split [
              ',',
              { Fn::ImportValue: !Sub '${App}-${Env}-PrivateSubnets' },
            ],
          ]

  ClientVpnAuthorizationRule:
    Condition: IsAllowedEnvironment
    Type: AWS::EC2::ClientVpnAuthorizationRule
    Properties:
      ClientVpnEndpointId: !Ref ClientVpnEndpoint
      TargetNetworkCidr: 0.0.0.0/0
      AuthorizeAllGroups: true
