-- AlterTable
ALTER TABLE `account` MODIFY `login_flg` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `deleted` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `account_group` MODIFY `create_account` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `update_corporation` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `admin_mode` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `update_store` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `sales_mode` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `update_store_setting` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `get_transaction_customer_info` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `set_transaction_manual_discount` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `create_transaction_return` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `create_buy_reception` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `assess_buy_transaction` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `finish_buy_transaction` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `set_buy_transaction_manual_product_price` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `list_item` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `list_original_pack` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `list_product` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `list_inventory` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `list_stocking_supplier` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `list_stocking` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `list_cash_history` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `list_transaction` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `list_customer` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `get_stats` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `list_purchase_table` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `announcement` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `announcement_store` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `app_advertisement` MODIFY `on_pause` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `deleted` TINYINT UNSIGNED NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `appraisal` MODIFY `shipping_date` DATE NOT NULL DEFAULT (CURRENT_DATE()),
    MODIFY `finished` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `billing_client` MODIFY `enabled` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `deleted` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `consignment_client` MODIFY `enabled` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `deleted` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    MODIFY `display_name_on_receipt` TINYINT UNSIGNED NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `contact` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `contract` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `contract_payment` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `corporation` MODIFY `square_available` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `enabled_staff_account` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `customer` MODIFY `is_active` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `customer_point_history` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `department` MODIFY `is_auto_registered` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `auto_update` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `hidden` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `is_deleted` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `device` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `ec_about_us` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `ec_message_center` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `ec_order` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `ec_order_cart_store` MODIFY `read` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `ec_order_cart_store_contact` MODIFY `myca_user_last_read_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `ec_order_cart_store_contact_message` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `ec_order_payment` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `ec_setting` MODIFY `auto_listing` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `auto_stocking` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `enable_same_day_shipping` TINYINT UNSIGNED NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `ec_wish_list` MODIFY `area_public` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `shipping_address_public` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `allow_other_products` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `bought_count_delay` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `ec_wish_list_product` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `gmo_credit_card` MODIFY `is_primary` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `inventory` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `inventory_shelf` MODIFY `is_deleted` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `item` MODIFY `is_buy_only` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `allow_auto_print_label` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `allow_round` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `infinite_stock` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `tablet_allowed` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    MODIFY `market_price_updated_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `hidden_products` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `jan_code_as_product_code` TINYINT UNSIGNED NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `item_calculate_history` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `item_category` MODIFY `hidden` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `deleted` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `ec_enabled` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `item_category_condition_option` MODIFY `deleted` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `item_genre` MODIFY `auto_update` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `hidden` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `deleted` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `ec_enabled` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `item_group` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `location` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `loss` MODIFY `datetime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `loss_genre` MODIFY `is_deleted` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `memo` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `myca_item` MODIFY `market_price_updated_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `outbox_ec_product_stock_history` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `outbox_product` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `pack_open_history` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `payment` MODIFY `bank__checked` TINYINT UNSIGNED NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `product` MODIFY `is_buy_only` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `mycalinks_ec_enabled` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `shopify_ec_enabled` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `ochanoko_ec_enabled` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `disable_ec_auto_stocking` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `is_active` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `arrow_auto_price_adjustment` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `force_no_price_label` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `is_special_price_product` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `allowed_point` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `tablet_allowed` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `deleted` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `sell_price_updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `buy_price_updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    MODIFY `allow_buy_price_auto_adjustment` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `allow_sell_price_auto_adjustment` TINYINT UNSIGNED NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE `product_ec_stock_history` MODIFY `datetime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `product_image` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `product_price` MODIFY `date` DATE NOT NULL DEFAULT (CURRENT_DATE());

-- AlterTable
ALTER TABLE `product_stock_history` MODIFY `datetime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `product_wholesale_price_history` MODIFY `arrived_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `is_exact` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `purchase_table` MODIFY `show_store_name` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    MODIFY `display_on_app` TINYINT UNSIGNED NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `purchase_table_item` MODIFY `any_model_number` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `is_psa10` TINYINT UNSIGNED NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `register` MODIFY `is_primary` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `auto_print_receipt_enabled` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `deleted` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    MODIFY `cash_reset_enabled` TINYINT UNSIGNED NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE `register_cash_history` MODIFY `datetime` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `register_settlement` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `data_end_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `register_status_history` MODIFY `run_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `reservation` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `reservation_reception` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `reservation_reception_product` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `sale` MODIFY `on_pause` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `sale_calculate_history` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `set_deal` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    MODIFY `is_deleted` TINYINT UNSIGNED NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `shipping_method` MODIFY `enabled_tracking` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `enabled_cash_on_delivery` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    MODIFY `deleted` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `is_all_in_one_fee` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `is_store_pickup` TINYINT UNSIGNED NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `specialty` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `stocking` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `store` MODIFY `opened` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `is_active` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `auto_print_receipt` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `allow_print_no_price_label` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `point_enabled` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `visit_point_enabled` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `sell_point_enabled` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `sell_point_limit_enabled` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `buy_point_enabled` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `buy_point_limit_enabled` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `point_spend_limit_enabled` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `point_expire_enabled` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `register_cash_reset_enabled` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `register_cash_manage_by_separately` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `mycalinks_ec_terms_accepted` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `mycalinks_ec_enabled` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `ochanoko_ec_enabled` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `shopify_ec_enabled` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `hide_non_mycalinks_item_on_tablet` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `hide_no_stock_product_on_tablet` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `hide_no_sell_price_product_on_tablet` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    MODIFY `include_tax` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `allow_duty_free` TINYINT UNSIGNED NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE `store_history` MODIFY `run_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `store_relation` MODIFY `mapping_defined` TINYINT UNSIGNED NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `store_shipment` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `supplier` MODIFY `enabled` TINYINT UNSIGNED NOT NULL DEFAULT true,
    MODIFY `deleted` TINYINT UNSIGNED NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `system_log` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `tablet_allowed_genre_category` MODIFY `no_specialty` TINYINT UNSIGNED NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `task` MODIFY `requested_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `task_item` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `template` MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP();

-- AlterTable
ALTER TABLE `transaction` MODIFY `is_return` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `hidden` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    MODIFY `finished_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    MODIFY `buy__is_assessed` TINYINT UNSIGNED NOT NULL DEFAULT false,
    MODIFY `can_create_signature` TINYINT UNSIGNED NOT NULL DEFAULT false;
