export const shippingConstants = {
  prefectureAreaDef: [
    { name: '北海道', belongsTo: ['北海道', '北海道エリア一律', '全国一律'] },
    { name: '青森県', belongsTo: ['青森県', '東北エリア一律', '全国一律'] },
    { name: '岩手県', belongsTo: ['岩手県', '東北エリア一律', '全国一律'] },
    { name: '宮城県', belongsTo: ['宮城県', '東北エリア一律', '全国一律'] },
    { name: '秋田県', belongsTo: ['秋田県', '東北エリア一律', '全国一律'] },
    { name: '山形県', belongsTo: ['山形県', '東北エリア一律', '全国一律'] },
    { name: '福島県', belongsTo: ['福島県', '東北エリア一律', '全国一律'] },
    { name: '茨城県', belongsTo: ['茨城県', '関東エリア一律', '全国一律'] },
    { name: '栃木県', belongsTo: ['栃木県', '関東エリア一律', '全国一律'] },
    { name: '群馬県', belongsTo: ['群馬県', '関東エリア一律', '全国一律'] },
    { name: '埼玉県', belongsTo: ['埼玉県', '関東エリア一律', '全国一律'] },
    { name: '千葉県', belongsTo: ['千葉県', '関東エリア一律', '全国一律'] },
    { name: '東京都', belongsTo: ['東京都', '関東エリア一律', '全国一律'] },
    { name: '神奈川県', belongsTo: ['神奈川県', '関東エリア一律', '全国一律'] },
    { name: '新潟県', belongsTo: ['新潟県', '信越エリア一律', '全国一律'] },
    { name: '長野県', belongsTo: ['長野県', '信越エリア一律', '全国一律'] },
    { name: '富山県', belongsTo: ['富山県', '北陸エリア一律', '全国一律'] },
    { name: '石川県', belongsTo: ['石川県', '北陸エリア一律', '全国一律'] },
    { name: '福井県', belongsTo: ['福井県', '北陸エリア一律', '全国一律'] },
    { name: '山梨県', belongsTo: ['山梨県', '東海エリア一律', '全国一律'] },
    { name: '岐阜県', belongsTo: ['岐阜県', '東海エリア一律', '全国一律'] },
    { name: '静岡県', belongsTo: ['静岡県', '東海エリア一律', '全国一律'] },
    { name: '愛知県', belongsTo: ['愛知県', '東海エリア一律', '全国一律'] },
    { name: '三重県', belongsTo: ['三重県', '近畿エリア一律', '全国一律'] },
    { name: '滋賀県', belongsTo: ['滋賀県', '近畿エリア一律', '全国一律'] },
    { name: '京都府', belongsTo: ['京都府', '近畿エリア一律', '全国一律'] },
    { name: '大阪府', belongsTo: ['大阪府', '近畿エリア一律', '全国一律'] },
    { name: '兵庫県', belongsTo: ['兵庫県', '近畿エリア一律', '全国一律'] },
    { name: '奈良県', belongsTo: ['奈良県', '近畿エリア一律', '全国一律'] },
    { name: '和歌山県', belongsTo: ['和歌山県', '近畿エリア一律', '全国一律'] },
    { name: '鳥取県', belongsTo: ['鳥取県', '中国エリア一律', '全国一律'] },
    { name: '島根県', belongsTo: ['島根県', '中国エリア一律', '全国一律'] },
    { name: '岡山県', belongsTo: ['岡山県', '中国エリア一律', '全国一律'] },
    { name: '広島県', belongsTo: ['広島県', '中国エリア一律', '全国一律'] },
    { name: '山口県', belongsTo: ['山口県', '中国エリア一律', '全国一律'] },
    { name: '徳島県', belongsTo: ['徳島県', '四国エリア一律', '全国一律'] },
    { name: '香川県', belongsTo: ['香川県', '四国エリア一律', '全国一律'] },
    { name: '愛媛県', belongsTo: ['愛媛県', '四国エリア一律', '全国一律'] },
    { name: '高知県', belongsTo: ['高知県', '四国エリア一律', '全国一律'] },
    { name: '福岡県', belongsTo: ['福岡県', '九州エリア一律', '全国一律'] },
    { name: '佐賀県', belongsTo: ['佐賀県', '九州エリア一律', '全国一律'] },
    { name: '長崎県', belongsTo: ['長崎県', '九州エリア一律', '全国一律'] },
    { name: '熊本県', belongsTo: ['熊本県', '九州エリア一律', '全国一律'] },
    { name: '大分県', belongsTo: ['大分県', '九州エリア一律', '全国一律'] },
    { name: '宮崎県', belongsTo: ['宮崎県', '九州エリア一律', '全国一律'] },
    { name: '鹿児島県', belongsTo: ['鹿児島県', '九州エリア一律', '全国一律'] },
    { name: '沖縄県', belongsTo: ['沖縄県', '沖縄エリア一律', '全国一律'] },
  ],
};

export const EC_PAYMENT_METHOD_MAP = {
  CARD: 'クレジットカード',
  PAYPAY: 'PayPay',
  CASH_ON_DELIVERY: '代引き',
  CONVENIENCE_STORE: 'コンビニ決済',
  BANK: '銀行振込',
} as const;
