name: production

version: 1

source:
  provider: GitHub
  properties:
    branch: production
    repository: https://github.com/Mycalinks/pos

stages:
  - name: production
    deployments:
      pos-web-app:
      ec-web-app:
        depends_on:
          - pos-web-app
      worker-ec-order:
      worker-item:
      worker-product:
      worker-transaction:
      worker-external-ec:
      worker-scheduled:
      worker-notification:
      job-daily-calculate:
      job-ensure-consistency:
      backend-outbox: # outbox監視

    post_deployments:
      Deploy-lambda-functions-production: # lambdaのデプロイ
        buildspec: ./copilot/pipelines/production/sam/buildspec.yml
