import { ArrivalTableType } from '@/feature/arrival/manage/arrivalList/type';
import { ArrivalStatus } from '@/feature/arrival/manage/arrivalStatus/Tabs';

export const arrivalData: ArrivalTableType[] = [
  {
    id: 1,
    status: ArrivalStatus.STILL,
    products: [
      'ブルーアイズ・ホワイト・ドラゴン',
      'ブラック・マジシャン',
      '真紅眼の黒竜',
    ],
    expectedArrivalData: '2024-09-17',
    arrivalData: '2024-09-17',
    supplier: 'カードショップA',
    arrivalStore: '店舗1',
    memo: '到着予定通り',
  },
  {
    id: 2,
    status: ArrivalStatus.DONE,
    products: ['ブラック・マジシャン'],
    expectedArrivalData: '2024-09-18',
    arrivalData: '2024-09-19',
    supplier: 'カードショップB',
    arrivalStore: '店舗2',
    memo: '到着が1日遅れた',
  },
  {
    id: 3,
    status: ArrivalStatus.STILL,
    products: ['真紅眼の黒竜'],
    expectedArrivalData: '2024-09-16',
    arrivalData: undefined,
    supplier: 'カードショップC',
    arrivalStore: '店舗3',
  },
  {
    id: 4,
    status: ArrivalStatus.DONE,
    products: ['青眼の究極竜'],
    expectedArrivalData: '2024-09-20',
    arrivalData: '2024-09-20',
    supplier: 'カードショップA',
    arrivalStore: '店舗1',
  },
  {
    id: 5,
    status: ArrivalStatus.ALL,
    products: ['レッド・デーモンズ・ドラゴン'],
    expectedArrivalData: '2024-09-21',
    arrivalData: '2024-09-21',
    supplier: 'カードショップB',
    arrivalStore: '店舗2',
    memo: '問題なく到着',
  },
  {
    id: 6,
    status: ArrivalStatus.STILL,
    products: ['オベリスクの巨神兵'],
    expectedArrivalData: '2024-09-22',
    arrivalData: '2024-09-23',
    supplier: 'カードショップC',
    arrivalStore: '店舗3',
  },
  {
    id: 7,
    status: ArrivalStatus.DONE,
    products: ['ラーの翼神竜'],
    expectedArrivalData: '2024-09-24',
    arrivalData: '2024-09-24',
    supplier: 'カードショップA',
    arrivalStore: '店舗1',
  },
  {
    id: 8,
    status: ArrivalStatus.ALL,
    products: ['サイバー・エンド・ドラゴン'],
    expectedArrivalData: '2024-09-25',
    arrivalData: '2024-09-26',
    supplier: 'カードショップB',
    arrivalStore: '店舗2',
  },
  {
    id: 9,
    status: ArrivalStatus.STILL,
    products: ['聖なるバリア - ミラーフォース'],
    expectedArrivalData: '2024-09-26',
    arrivalData: undefined,
    supplier: 'カードショップC',
    arrivalStore: '店舗3',
  },
  {
    id: 10,
    status: ArrivalStatus.DONE,
    products: ['千年竜'],
    expectedArrivalData: '2024-09-27',
    arrivalData: '2024-09-28',
    supplier: 'カードショップA',
    arrivalStore: '店舗1',
  },
  {
    id: 11,
    status: ArrivalStatus.STILL,
    products: ['カオス・ソルジャー'],
    expectedArrivalData: '2024-09-29',
    arrivalData: '2024-09-30',
    supplier: 'カードショップB',
    arrivalStore: '店舗2',
  },
  {
    id: 12,
    status: ArrivalStatus.DONE,
    products: ['デーモンの召喚'],
    expectedArrivalData: '2024-10-01',
    arrivalData: '2024-10-02',
    supplier: 'カードショップC',
    arrivalStore: '店舗3',
    memo: '無事到着',
  },
  {
    id: 13,
    status: ArrivalStatus.STILL,
    products: ['ダーク・ネクロフィア'],
    expectedArrivalData: '2024-10-03',
    arrivalData: undefined,
    supplier: 'カードショップA',
    arrivalStore: '店舗1',
  },
  {
    id: 14,
    status: ArrivalStatus.DONE,
    products: ['天空竜スフィアモード'],
    expectedArrivalData: '2024-10-04',
    arrivalData: '2024-10-05',
    supplier: 'カードショップB',
    arrivalStore: '店舗2',
  },
  {
    id: 15,
    status: ArrivalStatus.ALL,
    products: ['閃刀姫 - ロゼ'],
    expectedArrivalData: '2024-10-06',
    arrivalData: '2024-10-06',
    supplier: 'カードショップC',
    arrivalStore: '店舗3',
    memo: '配送に特に問題なし',
  },
  {
    id: 16,
    status: ArrivalStatus.STILL,
    products: ['エルシャドール・ネフィリム'],
    expectedArrivalData: '2024-10-07',
    arrivalData: '2024-10-08',
    supplier: 'カードショップA',
    arrivalStore: '店舗1',
  },
  {
    id: 17,
    status: ArrivalStatus.DONE,
    products: ['無限泡影'],
    expectedArrivalData: '2024-10-09',
    arrivalData: '2024-10-09',
    supplier: 'カードショップB',
    arrivalStore: '店舗2',
  },
  {
    id: 18,
    status: ArrivalStatus.ALL,
    products: ['イビリチュア・メロウガイスト'],
    expectedArrivalData: '2024-10-10',
    arrivalData: '2024-10-11',
    supplier: 'カードショップC',
    arrivalStore: '店舗3',
  },
  {
    id: 19,
    status: ArrivalStatus.STILL,
    products: ['エクシーズ・ユニバース'],
    expectedArrivalData: '2024-10-12',
    arrivalData: undefined,
    supplier: 'カードショップA',
    arrivalStore: '店舗1',
  },
  {
    id: 20,
    status: ArrivalStatus.DONE,
    products: ['ホーリーナイトドラゴン'],
    expectedArrivalData: '2024-10-13',
    arrivalData: '2024-10-14',
    supplier: 'カードショップB',
    arrivalStore: '店舗2',
  },
];
