name: Assign PR Creator

on:
  pull_request:
    types: [opened]

jobs:
  assign_creator:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR author as assignee
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const creator = pr.user.login;
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              assignees: [creator]
            });
