name: e2e
# developブランチに対してPRが作成されたタイミングをトリガーとする
on:
  pull_request:
    branches:
      - develop
      - staging
      - production
jobs:
  e2e:
    runs-on: myca-pos-actions-runner
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '23'
      - name: install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssl build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev g++

      - name: install pnpm
        run: npm i -g pnpm
      - name: install dependencies
        run: pnpm i --frozen-lockfile
      - name: prisma-generate
        run: pnpm run prisma:generate
      - name: backend-core
        run: pnpm run build:backend-core
      - name: common
        run: pnpm run build:common
      - name: api-generator
        run: pnpm api:generate && ls -la packages/api-generator/src/generated/client
      - name: Show memory usage before build
        run: free -h
      - name: web-app build
        run: cd packages/web-app && pnpm run e2e:build
      - name: Free disk space
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo df -h
      - name: Run E2E tests
        run: pnpx playwright install --with-deps && cd packages/web-app && pnpm run e2e:build && pnpm run test:e2e:minimum
      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: screenshots/
